service: serverless-nuxt

custom:
  optimize:
    debug: false

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.default

plugins:
  - serverless-plugin-optimize
